[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = 'cancun'
optimizer = false
viaIR = true
eth_rpc_url = "https://rpc.ankr.com/eth"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options